name: deploy
on: push

jobs:
  
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
            Port 9229
          END
        env:
          SSH_USER: ${{ secrets.DATA_USER }}
          SSH_KEY: ${{ secrets.DATA_SSHKEY}}
          SSH_HOST: ${{ secrets.DATA_HOSTIP }}

      - name: Stop the server
        run: ssh staging 'ls -la'

      - name: Check out the source
        run: ssh staging 'cd /~ && ls -la'
